# Generated by Django 4.2.5 on 2023-09-28 22:33

import autoslug.fields
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dealer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_modified', models.DateTimeField(auto_now=True, error_messages={'required': 'Данное поле обязательно для заполнения.'}, verbose_name='Дата последнего редактирования')),
                ('name', models.CharField(error_messages={'required': 'Данное поле обязательно для заполнения.'}, help_text='Укажите название дилера.', max_length=50, unique=True, verbose_name='Имя дилера')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, error_messages={'required': 'Данное поле обязательно для заполнения.'}, help_text='Ссылка на объект генерируется автоматически. Используется для адресации в URL-адресах.', populate_from='name', unique_with=['date_created'], verbose_name='Ссылка на объект')),
                ('date_created', models.DateTimeField(auto_now_add=True, error_messages={'required': 'Данное поле обязательно для заполнения.'}, help_text='Дата добавления дилера.', verbose_name='Дата добавления')),
            ],
            options={
                'verbose_name': 'Дилер',
                'verbose_name_plural': 'Дилеры',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_modified', models.DateTimeField(auto_now=True, error_messages={'required': 'Данное поле обязательно для заполнения.'}, verbose_name='Дата последнего редактирования')),
                ('first_name', models.CharField(error_messages={'required': 'Данное поле обязательно для заполнения.'}, max_length=30, verbose_name='Имя')),
                ('last_name', models.CharField(error_messages={'required': 'Данное поле обязательно для заполнения.'}, max_length=30, verbose_name='Фамилия')),
                ('surname', models.CharField(error_messages={'required': 'Данное поле обязательно для заполнения.'}, max_length=30, verbose_name='Отчество')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(error_messages={'required': 'Данное поле обязательно для заполнения.'}, help_text='Номер телефона сотрудника.', max_length=128, region=None, verbose_name='Номер телефона')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, error_messages={'required': 'Данное поле обязательно для заполнения.'}, help_text='Ссылка на объект генерируется автоматически. Используется для адресации в URL-адресах.', populate_from='first_name', unique_with=['last_name', 'date_created'], verbose_name='Ссылка на объект')),
                ('date_created', models.DateTimeField(auto_now_add=True, error_messages={'required': 'Данное поле обязательно для заполнения.'}, help_text='Укажите, когда был нанят данный сотрудник.', verbose_name='дата найма')),
                ('is_restricted', models.BooleanField(default=False, error_messages={'required': 'Данное поле обязательно для заполнения.'}, help_text='Отметьте, если сотрудник был уволен.', verbose_name='Сотрудник уволен')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_modified', models.DateTimeField(auto_now=True, error_messages={'required': 'Данное поле обязательно для заполнения.'}, verbose_name='Дата последнего редактирования')),
                ('title', models.CharField(error_messages={'required': 'Данное поле обязательно для заполнения.'}, help_text='Укажите название товара (до 120 символов).', max_length=120, verbose_name='Заголовок товара')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание товара')),
                ('price', models.IntegerField(error_messages={'invalid': 'Некорректное значение для цены товара.', 'required': 'Данное поле обязательно для заполнения.'}, help_text='Цена товара. Минимальное значение - 0 рублей.', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена товара')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, error_messages={'required': 'Данное поле обязательно для заполнения.'}, help_text='Ссылка на объект генерируется автоматически. Используется для адресации в URL-адресах.', populate_from='title', unique_with=['date_created'], verbose_name='Ссылка на объект')),
                ('quantity', models.IntegerField(blank=True, default=0, error_messages={'required': 'Данное поле обязательно для заполнения.'}, help_text='Укажите, сколько данного товара осталось на складе.', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Остаток на складе')),
                ('date_created', models.DateTimeField(auto_now_add=True, error_messages={'required': 'Данное поле обязательно для заполнения.'}, help_text='Дата создания автосалона.', verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='ProductSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, error_messages={'required': 'Данное поле обязательно для заполнения.'}, help_text='Ссылка на объект генерируется автоматически. Используется для адресации в URL-адресах.', populate_from='date_created', unique=True, verbose_name='Ссылка на объект')),
                ('date_created', models.DateTimeField(auto_now_add=True, error_messages={'required': 'Данное поле обязательно для заполнения.'}, help_text='Дата продажи товаров.', verbose_name='Дата продажи')),
                ('employee', models.ForeignKey(blank=True, error_messages={'required': 'Данное поля обязательно для заполнения.'}, help_text='Укажите, какой сотрудник продал данные товары.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sales', to='showroom.employee', verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Продажа',
                'verbose_name_plural': 'Продажи',
            },
        ),
        migrations.CreateModel(
            name='ProductSupply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, error_messages={'required': 'Данное поле обязательно для заполнения.'}, help_text='Ссылка на объект генерируется автоматически. Используется для адресации в URL-адресах.', populate_from='date_created', unique=True, verbose_name='Ссылка на объект')),
                ('supply_price', models.IntegerField(error_messages={'required': 'Данное поле обязательно для заполнения.'}, help_text='Укажите суммарную стоимость поставки.', verbose_name='Суммарная стоимость поставки')),
                ('date_created', models.DateTimeField(auto_now_add=True, error_messages={'required': 'Данное поле обязательно для заполнения.'}, help_text='Укажите дату совершения поставки.', verbose_name='Дата продажи')),
                ('dealer', models.ForeignKey(error_messages={'required': 'Данное поле обязательно для заполнения.'}, help_text='Укажите дилера, к которому должна быть привязана поставка.', on_delete=django.db.models.deletion.PROTECT, related_name='supplies', to='showroom.dealer', verbose_name='Дилер')),
            ],
            options={
                'verbose_name': 'Поставка товаров',
                'verbose_name_plural': 'Поставки товаров',
            },
        ),
        migrations.CreateModel(
            name='Showroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_modified', models.DateTimeField(auto_now=True, error_messages={'required': 'Данное поле обязательно для заполнения.'}, verbose_name='Дата последнего редактирования')),
                ('title', models.CharField(error_messages={'required': 'Данное поле обязательно для заполнения.'}, help_text='Название автосалона.', max_length=100, verbose_name='Название')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(error_messages={'required': 'Данное поле обязательно для заполнения.'}, help_text='Номер телефона для связи с автосалоном.', max_length=128, region=None, verbose_name='Номер телефона')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, error_messages={'required': 'Данное поле обязательно для заполнения.'}, help_text='Ссылка на объект генерируется автоматически. Используется для адресации в URL-адресах.', populate_from='title', unique_with=['date_created'], verbose_name='Ссылка на объект')),
                ('date_created', models.DateTimeField(auto_now_add=True, error_messages={'required': 'Данное поле обязательно для заполнения.'}, help_text='Дата создания автосалона.', verbose_name='Дата создания')),
                ('owner', models.ForeignKey(error_messages={'required': 'Данное поле обязательно для заполнения.'}, help_text='Владелец автосалона.', on_delete=django.db.models.deletion.CASCADE, related_name='showrooms', to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Автосалон',
                'verbose_name_plural': 'Автосалоны',
            },
        ),
        migrations.CreateModel(
            name='ProductSupplyItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(error_messages={'required': 'Данное поля обязательно для заполнения.'}, help_text='Укажите, какое кол-во данного товара было поставлено.', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Кол-во поставленного товара')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, error_messages={'required': 'Данное поле обязательно для заполнения.'}, help_text='Ссылка на объект генерируется автоматически. Используется для адресации в URL-адресах.', populate_from='product__title', unique_with=['date_created'], verbose_name='Ссылка на объект')),
                ('supply_price', models.IntegerField(error_messages={'invalid': 'Значение данного поля должно начинаться с 0', 'required': 'Данное поля обязательно для заполнения.'}, help_text='Укажите цену поставленного товара за одну штуку.', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена поставленного товара')),
                ('date_created', models.DateTimeField(auto_now_add=True, error_messages={'required': 'Данное поле обязательно для заполнения.'}, help_text='Дата поставки товара.', verbose_name='Дата поставки')),
                ('product', models.ForeignKey(error_messages={'required': 'Данное поля обязательно для заполнения.'}, help_text='Укажите, какой товар был поставлен.', on_delete=django.db.models.deletion.DO_NOTHING, related_name='supplied_products', to='showroom.product', verbose_name='Поставленный товар')),
                ('supply', models.ForeignKey(error_messages={'required': 'Данное поля обязательно для заполнения.'}, help_text='Укажите, к какой поставке относится данный товар.', on_delete=django.db.models.deletion.CASCADE, related_name='supplied_products', to='showroom.productsupply', verbose_name='Поставка')),
            ],
            options={
                'verbose_name': 'Товар поставки',
                'verbose_name_plural': 'Товары поставки',
            },
        ),
        migrations.AddField(
            model_name='productsupply',
            name='showroom',
            field=models.ForeignKey(error_messages={'required': 'Данное поле обязательно для заполнения.'}, help_text='Укажите автосалон, к которому должна быть привязана поставка.', on_delete=django.db.models.deletion.CASCADE, related_name='supplies', to='showroom.showroom', verbose_name='Автосалон'),
        ),
        migrations.CreateModel(
            name='ProductSaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(error_messages={'invalid': 'Значение данного поля должно начинаться с 0', 'required': 'Данное поля обязательно для заполнения.'}, help_text='Укажите, какое кол-во данного товара было продано.', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Кол-во проданного товара')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, error_messages={'required': 'Данное поле обязательно для заполнения.'}, help_text='Ссылка на объект генерируется автоматически. Используется для адресации в URL-адресах.', populate_from='product__title', unique_with=['date_created'], verbose_name='Ссылка на объект')),
                ('sale_price', models.IntegerField(error_messages={'invalid': 'Значение данного поля должно начинаться с 0', 'required': 'Данное поля обязательно для заполнения.'}, help_text='Укажите цену проданного товара за одну штуку.', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена проданного товара')),
                ('date_created', models.DateTimeField(auto_now_add=True, error_messages={'required': 'Данное поле обязательно для заполнения.'}, help_text='Дата создания товара продажи.', verbose_name='Дата создания')),
                ('product', models.ForeignKey(error_messages={'required': 'Данное поля обязательно для заполнения.'}, help_text='Укажите, какой товар был продан.', on_delete=django.db.models.deletion.DO_NOTHING, related_name='sold_products', to='showroom.product', verbose_name='Проданный товар')),
                ('sale', models.ForeignKey(error_messages={'invalid': 'Значение данного поля должно начинаться с 0', 'required': 'Данное поля обязательно для заполнения.'}, help_text='Укажите, к какой продаже относится данный товар.', on_delete=django.db.models.deletion.CASCADE, related_name='sold_products', to='showroom.productsale', verbose_name='Продажа')),
            ],
            options={
                'verbose_name': 'Товар продажи',
                'verbose_name_plural': 'Товары продажи',
            },
        ),
        migrations.AddField(
            model_name='productsale',
            name='showroom',
            field=models.ForeignKey(error_messages={'required': 'Данное поле обязательно для заполнения.'}, help_text='Укажите автосалон, к которому должен быть привязан товар.', on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='showroom.showroom', verbose_name='Автосалон'),
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_modified', models.DateTimeField(auto_now=True, error_messages={'required': 'Данное поле обязательно для заполнения.'}, verbose_name='Дата последнего редактирования')),
                ('name', models.CharField(error_messages={'required': 'Данное поле обязательно для заполнения.', 'unique': 'Название категории должно быть уникальным. Данная категория уже существует.'}, help_text='Название категории. Должно быть уникальным.', max_length=70, unique=True, verbose_name='Название')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, error_messages={'required': 'Данное поле обязательно для заполнения.'}, help_text='Ссылка на объект генерируется автоматически. Используется для адресации в URL-адресах.', populate_from='name', unique_with=['date_created'], verbose_name='Ссылка на объект')),
                ('date_created', models.DateTimeField(auto_now_add=True, error_messages={'required': 'Данное поле обязательно для заполнения.'}, help_text='Дата создания автосалона.', verbose_name='Дата создания')),
                ('showroom', models.ForeignKey(error_messages={'required': 'Данное поле обязательно для заполнения.'}, help_text='Укажите автосалон, к которому должна быть привязана категория товаров.', on_delete=django.db.models.deletion.CASCADE, related_name='product_categories', to='showroom.showroom', verbose_name='Автосалон')),
            ],
            options={
                'verbose_name': 'Категория товаров',
                'verbose_name_plural': 'Категории товаров',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(error_messages={'required': 'Данное поле обязательно для заполнения.'}, help_text='Укажите категорию товара.', on_delete=django.db.models.deletion.CASCADE, related_name='products', to='showroom.productcategory', verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='product',
            name='showroom',
            field=models.ForeignKey(error_messages={'required': 'Данное поле обязательно для заполнения.'}, help_text='Укажите автосалон, к которому должен быть привязан товар.', on_delete=django.db.models.deletion.CASCADE, related_name='products', to='showroom.showroom', verbose_name='Автосалон'),
        ),
        migrations.AddField(
            model_name='employee',
            name='showroom',
            field=models.ForeignKey(error_messages={'required': 'Данное поле обязательно для заполнения.'}, help_text='Укажите автосалон, к которому должен быть привязан данный сотрудник.', on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='showroom.showroom', verbose_name='Автосалон'),
        ),
    ]
