# Generated by Django 4.2.5 on 2023-09-29 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showroom', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.RemoveField(
            model_name='productsupply',
            name='supply_price',
        ),
        migrations.AddField(
            model_name='dealer',
            name='is_active',
            field=models.BooleanField(default=True, error_messages={'required': 'Данное поле обязательно для заполнения.'}, help_text='Отметьте, если хотите сделать дилера активный или наоборот.', verbose_name='Дилер активен'),
        ),
    ]
