# Generated by Django 4.2.5 on 2023-09-28 23:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_customuser_date_joined_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, error_messages={'required': 'Данное поле обязательно для заполнения.'}, help_text='Дата регистрации пользователя.', verbose_name='Дата регистрации'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='date_password_updated',
            field=models.DateTimeField(default=django.utils.timezone.now, error_messages={'required': 'Данное поле обязательно для заполнения.'}, help_text='Дата последней смены пароля пользователя.', verbose_name='Дата смены пароля'),
        ),
    ]
