# Generated by Django 4.2.5 on 2023-09-28 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_customuser_date_joined_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customuser',
            table='auth_user',
        ),
    ]
