from django.urls import path
from . import views

urlpatterns = [
    path(
        'login/',
        views.CustomLoginView.as_view(),
        name='login'
    ),
    path(
        'registration/',
        views.CustomRegistrationView.as_view(),
        name='registration'
    ),
    path(
        'logout/',
        views.CustomLogoutView.as_view(),
        name='logout'
    ),
    path(
        'password_reset/',
        views.CustomPasswordResetView.as_view(),
        name='reset_password'
    ),
    path(
        'password_reset/done',
        views.CustomPasswordResetDoneView.as_view(),
        name='password_reset_done'
    ),
    path(
        'password_reset/<uidb64>/<token>',
        views.CustomPasswordResetConfirmView.as_view(),
        name='password_reset_confirm'
    ),
    path(
        'password_change/',
        views.CustomPasswordChangeView.as_view(),
        name='password_change'
    ),
    path(
        'profile/',
        views.ProfileView.as_view(),
        name='profile'
    ),
    path(
        'profile/edit/',
        views.ProfileEditView.as_view(),
        name='profile_edit'
    ),
    path(
        'email_verification/send/',
        views.EmailVerificationSend.as_view(),
        name='email_verification_send'
    ),
    path(
        'email_verification/<uidb64>/<token>/',
        views.EmailVerificationCheckView.as_view(),
        name='email_verification_check'
    ),
    path(
        'email_verification/',
        views.EmailVerificationInfoView.as_view(),
        name='email_verification_info'
    ),

    path(
        'email_verification/edit/',
        views.EmailVerificationInfoView.as_view(),
        name='email_verification_edit'
    )
]
